apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner-service-account
  namespace: github-actions-runner

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-runner-role
  namespace: github-actions-runner
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-runner-rolebinding
  namespace: github-actions-runner
subjects:
- kind: ServiceAccount
  name: github-runner-service-account
  namespace: github-actions-runner
roleRef:
  kind: Role
  name: github-runner-role
  apiGroup: rbac.authorization.k8s.io